### ISSUE TITLE
Scene header error

### ISSUE THREAD

**Issue by jocago** [ludovicchabant/Jouvence#1]
Using the "." as an indicator that a line is the header for a scene causes an issue if the line actually begin with an ellipsis (...). The specification should require an alphanumeric character immediately following the '.' in order for it to be considered a scene header.

**Comment by ludovicchabant** [comment]
The [specification](https://fountain.io/syntax#section-overview) does require it actually: 

> Note that only a single leading period followed by an alphanumeric character will force a Scene Heading. This allows the writer to begin Action and Dialogue elements with ellipses without worry that they'll be interpreted as Scene Headings.

I was just missing that check... fixed with 9d1d9b62547ee3c49d7647ae52811357779e673a, thanks!
