### ISSUE TITLE
Synopsis → Synopses

### ISSUE THREAD

**Issue by lenormf** [ludovicchabant/Jouvence#2]
Hi,

There's a typo in the codebase:

https://fountain.io/syntax#section-sections

HTH.

**Comment by ludovicchabant** [comment]
The fountain.io website is unaffiliated with the Jouvence project... Jouvence just implements the standard described there.

**Comment by lenormf** [comment]
The proper term is “synopse” but Jouvence uses “synopsis” for some reason… that's incorrect.
