### ISSUE TITLE
Convert a string to a screenplay formatted string?

### ISSUE THREAD

**Issue by tin2tin** [ludovicchabant/Jouvence#3]
How do I convert a string into a screenplay formatted(indented etc.) monospaced text string in python code?

**Comment by ludovicchabant** [comment]
You could implement your own subclass of `jouvence.renderer.BaseTextRenderer` and `jouvence.renderer.BaseDocumentRenderer`. And then you do:

```
from jouvence.parser import JouvenceParser
from jouvence.html import YourDocumentRenderer

parser = JouvenceParser()
document = parser.parse(path_to_file)
renderer = YourDocumentRenderer()
with open(path_to_output, 'w') as fp:
  renderer.render_doc(document, fp)
```

You can get some inspiration from the HTML and console renderers.
